title: U.S. Aid to Security Sector Actors
description: "A comprehensive, global tracking of unclassified U.S. security assistance from 2000 to 2026 (Q1). By <strong><a href='https://plsullivan.web.unc.edu/' target='_blank' style='color: #f8fafc; font-weight: bold;'>Patricia Sullivan</a> &amp; <a href='https://giovannyralvarez.github.io/' target='_blank' style='color: #f8fafc; font-weight: bold;'>Giovanny Alvarez</a></strong>."
theme: jekyll-theme-cayman
navigation:
  - title: Home
    url: /
  - title: Dataset Versions
    url: /dataset.html
  - title: Publications
    url: /papers.html
